// Listens to the "changeFilter" event dispatched in Card.js inside the cardFooter's click event listener to change the value of the data-selected attribute and the selected button's style. This structure comes to solve a problem generated by having simultaneous event listeners for the same event that executed linked code, this wasy we make sure that this function will be called only after the rest of logic inside Card.js
document
  .getElementById("cardFooter")
  .addEventListener("changeFilter", (event) => {
    // Cuts the function if the list of tasks is closed
    if (!document.getElementById("dropdown").checked) {
      return;
    }
    // We access the list of buttons in the cardFooter by querying them with their element's type selector.
    // Then loop through each one of them with the forEach method and uses and anonymous function to give the selected style only to the button which id is equal to the event.detail
    document
      .getElementById("cardFooter")
      .querySelectorAll("[data-selected]")
      .forEach((button) => {
        if (button.id === event.detail) {
          button.style.border = "1.5px solid #f5e4e4";
          button.dataset.selected = "true";
        } else {
          button.style.border = "none";
          button.dataset.selected = "false";
        }
      });
  });
